name: EnergyControl
description: "Кросс-платформенное мобильное приложение для мониторинга соответствия законодательным нормам в нефтегазовой отрасли"
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: 24.2.6
  http: ^1.2.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
